_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.12.2
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 1
                - 16
                - 23
                - 55
                - 62
            "4": 3.12.2
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": darwin-arm64
batch:
    value: 16
crop:
    value: 44100
dataset:
    value: dataset
epochs:
    value: 2
lr:
    value: 0.0003
max_batches:
    value: 5
save_dir:
    value: checkpoints
subset:
    value: 32
wandb:
    value: true
wandb_entity:
    value: null
wandb_project:
    value: audio-denoise-demo
workers:
    value: 4
